require:
  - rubocop

plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4.5
  NewCops: enable
  Exclude:
    - bin/*

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/MethodLength:
  Max: 12
